name: TOML & MITRE Validation

on:
  push:
  workflow_dispatch:

jobs:
  toml-mitre_validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - run: pip install requests
      - run: python development/validation.py
      - run: python development/mitre.py
